Models/DeviceModel.cs
using System.Diagnostics.Eventing.Reader;

namespace SeniorProject.Models
{
    public class DeviceModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Alert { get; set; }
        public bool Powered {  get; set; }

        public DeviceModel (int id, string name, bool alert, bool powered)
        {
            Id = id;
            Name = name;
            Alert = alert;
            Powered = powered;
        }
    }
}

Models/ErrorViewModel.cs
namespace SeniorProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/DevicesController.cs
using Microsoft.AspNetCore.Mvc;
using SeniorProject.Models;
using SeniorProject.Services;
using System.Diagnostics;

namespace SeniorProject.Controllers
{
    public class DevicesController : Controller
    {
        public IActionResult Devices()
        {
            //using this file for implementing a better code structure rather than hard-coding it here
            HardCodedSampleDataRepository repository = new HardCodedSampleDataRepository();

            return View(repository.AllProducts());
        }
        public IActionResult EditDevice()
        {
            return View();
        }

        public IActionResult AddDevice()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SeniorProject.Models;
using System.Diagnostics;

namespace SeniorProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Devices()
        {
            return View();
        }
        public IActionResult Settings()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Devices/AddDevice.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add A Device ";
}


<script>
    if (localStorage.getItem('dark')) {
        body.classList.add('dark');
    }
</script>

<html>
    <p>This is where new devices will be added</p>

</html>




<script>
    checkbox.addEventListener('change', darkModeToggle() {
        localStorage.setItem('dark', this.checked);
        if (this.checked) {
            body.classList.add('dark')
        } else {
            body.classList.remove('dark')
        }
    });

</script>

Views/Devices/Devices.cshtml
@model IEnumerable<SeniorProject.Models.DeviceModel>

<script>
    if (localStorage.getItem('dark')) {
        body.classList.add('dark');
    }
</script>

<p>
    <a asp-controller="Devices" asp-action="AddDevice">Add Device +</a>
</p>
<table class="table">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Alert)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Powered)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Alert)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Powered)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditDevice", "Devices",  new { /*id=item.PrimaryKey */ } ) |
               @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ }) 
            </td>
        </tr>
}
    </tbody>
</table>

<script>
    checkbox.addEventListener('change', darkModeToggle() {
        localStorage.setItem('dark', this.checked);
        if (this.checked) {
            body.classList.add('dark')
        } else {
            body.classList.remove('dark')
        }
    });

</script>

Views/Devices/EditDevice.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Edit A Device";
}


<script>
    if (localStorage.getItem('dark')) {
        body.classList.add('dark');
    }
</script>


<html>

    <body>
        <p>This is where devices will be edited</p>
    </body>

</html>

<script>
    checkbox.addEventListener('change', darkModeToggle() {
        localStorage.setItem('dark', this.checked);
        if (this.checked) {
            body.classList.add('dark')
        } else {
            body.classList.remove('dark')
        }
    });

</script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<script>
    if (localStorage.getItem('dark')) {
        body.classList.add('dark');
    }
</script>


<div class="text-center">
    <h1 class="display-4">Recent Alerts</h1>
    <p>Recentlt alerted devices will be displayed here.</p>
</div>

<div align="center" >
    <div class="box">Bird Watcher
        <a href="https://the-gadgeteer.com/wp-content/uploads/2021/05/blinkcam-birdcam-6.jpg">
            <p>
                View Alert
            </p>
        </a>
    </div>
    <p></p>
    <div class="box">Door Cam
        <a href="https://www.cnet.com/a/img/resize/5b94304f2e405e23712a6c3ef2ff05e24365fa33/hub/2023/03/08/92644bdd-ebca-4994-b802-8b16dcc2be46/ring-battery-doorbell-plus.jpg?auto=webp&fit=crop&height=675&width=1200">
            <p>
                View Alert
            </p>
        </a>
    </div>
    <p></p>
    <div class="box">Livingroom Cam <br />

        <a href="https://shotkit.com/wp-content/uploads/2022/04/petcube-play-2-5-quality-2.jpg"
            <p>
                View Alert
            </p>
        </a>
    </div>
</div>




















<script>
    checkbox.addEventListener('change', darkModeToggle() {
        localStorage.setItem('dark', this.checked);
        if (this.checked) {
            body.classList.add('dark')
        } else {
            body.classList.remove('dark')
        }
    });

</script>

Views/Home/Settings.cshtml
@{
    ViewData["Title"] = "Settings";

}
<script>
    if (localStorage.getItem('dark')) {
        body.classList.add('dark');
    }
</script>

<h1>@ViewData["Title"]</h1>



<body>
    <div>
        <div class="miniTitles">Change Colors: </div>
        <div>
            <button onclick="darkModeToggle()">Toggle Light/Dark</button>
        </div>
    </div>
 
</body>

<script>
    checkbox.addEventListener('change', darkModeToggle() {
        localStorage.setItem('dark', this.checked);
        if (this.checked) {
            body.classList.add('dark')
        } else {
            body.classList.remove('dark')
        }
    });

</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SeniorProject</title>

    <meta name="color-scheme" content="light dark" />


    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />-->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SeniorProject.styles.css" asp-append-version="true" />



</head>
<body>


    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SeniorProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Devices" asp-action="Devices">Devices</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Settings">Settings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SeniorProject - <a asp-area="" asp-controller="Home" asp-action="Devices">Devices</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>


</html>